In [20]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.neural_network import MLPClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import VotingClassifier

In [21]:
import joblib
model = joblib.load('new_data/combinedModel.sav')

## Trump

In [22]:
trump_posts = pd.read_csv('dataset/trump.csv')
trump_posts2 = trump_posts.drop(trump_posts.columns[0], axis=1)
trump_posts_list = trump_posts[trump_posts2.columns[0]].values.tolist()
trump_posts_list[:5]

['If you tell me a "being of pure white light" speaks to Donald J. #Trump, I\'ll wonder if they were #Elohim.',
 '.@TheDemocrats in 2016: "Don\'t vote for #Trump, he will start new wars!!!"\n\n@TheDemocrats in 2020: "Don\'t vote for… https://t.co/qcjcBxxWFD',
 "@4Awesometweet I'm sure #trump will find a way to compliment himself.",
 "@MikeHun84192140 @JadeisFedUp @MPFIED @davematt88 Really?  How?  Name one thing that #Trump has done that's best of… https://t.co/WGYV3RlGTJ",
 "@mitchellvii Best outcome: you're purposely trolling.\n\nWorst outcome: You and the people who rely on you for… https://t.co/yZW1GqXLGF"]

In [23]:
X_trump = np.genfromtxt('X_trump.csv', delimiter=',')[1:]
X_trump

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [24]:
Y_trump = model.predict_proba(X_trump)
Y_trump

array([[0.26284019, 0.73715981],
       [0.33102541, 0.66897459],
       [0.3317598 , 0.6682402 ],
       ...,
       [0.60372298, 0.39627702],
       [0.227561  , 0.772439  ],
       [0.68050409, 0.31949591]])

In [25]:
#trump
positive = 0
negative = 0
neutral = 0

positive_list, negative_list = [], []

for i,p in enumerate(Y_trump):

    if p[1] > 0.6: 
        positive += 1
        if p[1] > 0.9:
            positive_list.append(trump_posts_list[i])

    elif p[1] < 0.4:
        negative += 1
        if p[1] < 0.1:
            negative_list.append(trump_posts_list[i])
    else:
        neutral += 1
    
print((positive/len(Y_trump))*100,"% holds a positive attitude towards trump")
print((negative/len(Y_trump))*100,"% holds a negative attitude towards trump")
print((neutral/len(Y_trump))*100,"% holds a neutral attitude towards trump")

print('\n\n\n')
print("Positive:")
for p in positive_list:
    print(p)
    
print('\n\n\n')
print("Negative:")
for p in negative_list:
    print(p)

45.9 % holds a positive attitude towards trump
17.5 % holds a negative attitude towards trump
36.6 % holds a neutral attitude towards trump




Positive:
I'm kinda glad that #Trump is encouraging his #StuckonTrumpers to vote for Sanders in primary. I'm ready for the Un… https://t.co/zYJdCK1Su5
@wwdnet2 Beautiful Twitter header. Just beautiful. #TRUMP
#Trump Says: I will be having a 1:30 P.M. Press Conference at the White House to discuss the latest CoronaVirus developments. Thank you!
#CoronavirusOutbreak

Be sure to thank @realDonaldTrump and @RichforGA for a rational response🙏🇺🇸

Instead of… https://t.co/cT0FTgKa74
You’re not welcome. And if you do not let your qualified scientists and health experts speak, we can’t believe anyt… https://t.co/ywf7Z0YATk
You're feeling pretty happy Trump! Is your failing Scottish golf resort finally doing well?
 In response to:… https://t.co/X7mAEqZg0K
#Trump Says: THANK YOU SOUTH CAROLINA! 
https://t.co/RSEelakGwC
Glad you are joining us for a trip d

## coronavirus

In [13]:
coronavirus_posts = pd.read_csv('dataset/coronavirus.csv')
coronavirus_posts2 = coronavirus_posts.drop(coronavirus_posts.columns[0], axis=1)
coronavirus_posts_list = coronavirus_posts[coronavirus_posts2.columns[0]].values.tolist()
coronavirus_posts_list[:5]

['@RealJamesWoods Last 18 hours:\nOur #POTUS45 ...\n✅ Huge Trump Rally in Charleston 12,000 plus\n✅ Conveens Emergency… https://t.co/E0VDvyLzpg',
 '@SecAzar WE THE PEOPLE ARE NOT* PAYING TO GET TREATED FOR THE #CORONAVIRUS. I’m reading reports Americans are recei… https://t.co/pOVP80M9xg',
 'As of 29/02/2020. Confirmed cases in areas outside PRC are picking up speed.\n#nCoV19 #coronavirus #COVID19… https://t.co/gbgc5OqPsW',
 'Pope confirmed to have #COVID19 #CoronaVirus.... Coincidence? I think NOT...',
 '@MrTommyCampbell A new case in Ajax, close to where I live.\nSick stay home.\n#coronavirus']

In [14]:
X_coronavirus = np.genfromtxt('X_coronavirus.csv', delimiter=',')[1:]
X_coronavirus

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [15]:
Y_coronavirus = model.predict_proba(X_coronavirus)
Y_coronavirus

array([[0.64185727, 0.35814273],
       [0.38819136, 0.61180864],
       [0.45858073, 0.54141927],
       ...,
       [0.57305556, 0.42694444],
       [0.71448218, 0.28551782],
       [0.67736294, 0.32263706]])

In [18]:
positive = 0
negative = 0
neutral = 0

positive_list = []
negative_list = []

for i,p in enumerate(Y_coronavirus):

    if p[1] > 0.6: 
        positive += 1
        if p[1] > 0.9:
            positive_list.append(coronavirus_posts_list[i])

    elif p[1] < 0.4:
        negative += 1
        if p[1] < 0.1:
            negative_list.append(coronavirus_posts_list[i])
    else:
        neutral += 1
    
print((positive/len(Y_coronavirus))*100,"% holds a positive attitude towards coronavirus")
print((negative/len(Y_coronavirus))*100,"% holds a negative attitude towards coronavirus")
print((neutral/len(Y_coronavirus))*100,"% holds a neutral attitude towards coronavirus")

for p in positive_list:
    print(p)
    
print('\n\n\n')
print("Negative:")
for p in negative_list:
    print(p)

41.4 % holds a positive attitude towards coronavirus
25.2 % holds a negative attitude towards coronavirus
33.4 % holds a neutral attitude towards coronavirus
Attention: Event Organizers! 

A great read from @rwang0 on the best practices for hosting events while we are deal… https://t.co/2Zzi35elKb
#Repost 9gag (@get_repost)
・・・
sing Happy Birthday twice⠀
-⠀
#washyourhands #9gag #coronavirus https://t.co/naUskKA0i1
As #Coronavirus hits Europe, check out our latest blog post about how Social Media Platforms are tackling fake Covi… https://t.co/yM3iYrGgY5
#COVID19 #CustomerService
#cruisingwithdon
#cruiseshipnews
#coronavirus

Thank you for such generosity and great cu… https://t.co/Y7zy68TxAu
@connecticuck #coronavirus 
#Connzuela
@toddtalk 
See above,Todd 
Thank you




Negative:
@MrTommyCampbell A new case in Ajax, close to where I live.
Sick stay home.
#coronavirus
@Gopgirl719 Sorry to hear. I too have a condition with my stomach that if I got the #CoronaVirus it could kill me too. Ve

## MeToo

In [5]:
metoo_posts = pd.read_csv('dataset/Metoomovement.csv')
metoo_posts2 = metoo_posts.drop(metoo_posts.columns[0], axis=1)
metoo_posts_list = metoo_posts[metoo_posts2.columns[0]].values.tolist()
metoo_posts_list[:5]

['@aeryn_thrace The latest #Metoomovement.\n\nhttps://t.co/UXnyPVHdBl https://t.co/YA2PLXviM8',
 '@miriamsved - involved in a wonderful discussion about the #Metoomovement with @LaTrioli yesterday. When asked if t… https://t.co/S9pqAhwJNs',
 '@fawazar94 That show talks about #media and the #MeTooMovement in a very interesting way. Well-received',
 '@raveninak @BridgetSterli19 She joined the #Metoomovement',
 '@JoJoFromJerz Did the flag give consent???? Then again, has that ever stopped him before??? #metoo #Metoomovement @Alyssa_Milano']

In [6]:
X_metoo = np.genfromtxt('X_metoo.csv', delimiter=',')[1:]
X_metoo

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [8]:
Y_metoo = model.predict_proba(X_metoo)
Y_metoo[:5]

array([[0.45022353, 0.54977647],
       [0.4121008 , 0.5878992 ],
       [0.25135349, 0.74864651],
       [0.42910483, 0.57089517],
       [0.27249235, 0.72750765]])

In [19]:
positive = 0
negative = 0
neutral = 0

positive_list = []
negative_list = []

for i,p in enumerate(Y_metoo):

    if p[1] > 0.6: 
        positive += 1
        if p[1] > 0.9:
            positive_list.append(metoo_posts_list[i])

    elif p[1] < 0.4:
        negative += 1
        if p[1] < 0.1:
            negative_list.append(metoo_posts_list[i])
    else:
        neutral += 1
    
print((positive/len(Y_metoo))*100,"% holds a positive attitude towards metoo")
print((negative/len(Y_metoo))*100,"% holds a negative attitude towards metoo")
print((neutral/len(Y_metoo))*100,"% holds a neutral attitude towards metoo")

print('\n\n\n')
print("Positive:")
for p in positive_list:
    print(p)
    
print('\n\n\n')
print("Negative:")
for p in negative_list:
    print(p)

46.253229974160206 % holds a positive attitude towards metoo
19.379844961240313 % holds a negative attitude towards metoo
34.366925064599485 % holds a neutral attitude towards metoo




Positive:
y’all love the #Metoomovement and applaud women for standing up to their attackers until ur favorite athlete gets a… https://t.co/uREhAhPUAn
Thank you @TaranaBurke for leading America by founding the #Metoomovement.  Hopefully the conviction of… https://t.co/JDzYsmi8zW
Congrats #MeToo #Metoomovement on success w/Weinstein &amp; Cosby finally paying for their many crimes, but w/24+ claim… https://t.co/KKwu3pjz4t
Thank you brave women #metoo #Metoomovement for bringing light to this toxic norm of the 20th century. #shesaid… https://t.co/FnWPfcGxLs
He’s finally getting locked up! 🥳 It’s a good morning! #HarveyWeinsteinGuilty #MeTooMovement https://t.co/wRy097iRZt
Help yourself cope by getting tons of ppl signed up to vote. Back and follow @KamalaHarris  join #metoomovement. It… https://t.co/BCrkA