In [18]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.neural_network import MLPClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import VotingClassifier

In [83]:
X = np.genfromtxt('data/X.csv', delimiter=',')
Y = np.genfromtxt('data/Y.csv', delimiter=',')
tradewar_posts = pd.read_csv('dataset/tradewar.csv')

In [92]:
tradewar_posts2 = tradewar_posts.drop(tradewar_posts.columns[0], axis=1)
tradewar_posts_list = tradewar_posts[tradewar_posts2.columns[0]].values.tolist()
tradewar_posts_list

['@ubendor @Abby4Iowa Actually no, John Deere has outsourced so many parts to China in the past 10 years. There are m… https://t.co/8TLgkzUjW4',
 "@shaver50 @Abby4Iowa Layoffs in Waterloo don't take effect until May 4th. No John Deere has no regular layoffs, my… https://t.co/0rG3Ec9Lpn",
 '#Trump provides government "#Socialism" to #TradeWar struggling US farmers &amp; culinary industry. #Takers… https://t.co/tjK5ET6IZg',
 'Did you miss this Gary Shilling Interview? With recent #coronavirusupdates we now know that the Coronavirus has spr… https://t.co/g4XULnUmbF',
 '#maga #washyourhands #cdc #politics #elections #tradewar #hkprorestors #nyse Another tool for division.. we are the… https://t.co/jqRwmlq0eo',
 'Can our #Security be guaranteed by only letting Huawei build a periphery 5G network?\r\nhttps://t.co/tb5fLjsvxd\r\n#5G… https://t.co/uugCWWQ31c',
 '#Trade Wars: Substance, Nonsense and the Thucydides Trap\r\n#Financial #InternationalTrade #StockMarket… https://t.co/GLxT9fTb9X',
 'I

In [95]:
trump_posts = pd.read_csv('dataset/trump.csv')
trump_posts2 = trump_posts.drop(trump_posts.columns[0], axis=1)
trump_posts_list = trump_posts[trump_posts2.columns[0]].values.tolist()
trump_posts_list

['If you tell me a "being of pure white light" speaks to Donald J. #Trump, I\'ll wonder if they were #Elohim.',
 '.@TheDemocrats in 2016: "Don\'t vote for #Trump, he will start new wars!!!"\r\n\r\n@TheDemocrats in 2020: "Don\'t vote for… https://t.co/qcjcBxxWFD',
 "@4Awesometweet I'm sure #trump will find a way to compliment himself.",
 "@MikeHun84192140 @JadeisFedUp @MPFIED @davematt88 Really?  How?  Name one thing that #Trump has done that's best of… https://t.co/WGYV3RlGTJ",
 "@mitchellvii Best outcome: you're purposely trolling.\r\n\r\nWorst outcome: You and the people who rely on you for… https://t.co/yZW1GqXLGF",
 ".\r\nWashington state woman becomes first American fatality from Fucking Moron #Trump's #coronavirus #hoax… https://t.co/iT1h86bVNn",
 "#Trump is actively encouraging\r\nmagas\r\nto #Vote for @BernieSanders\r\nwhy you ask?\r\nso he\r\n&amp;\r\nhis 'followers'\r\ncan SCREAM… https://t.co/LIUZSLSVPG",
 "#CoronaVirus. #Biden contro #Trump. 'Absolutely dangerous': Biden sl

In [96]:
coronavirus_posts = pd.read_csv('dataset/coronavirus.csv')
coronavirus_posts2 = coronavirus_posts.drop(coronavirus_posts.columns[0], axis=1)
coronavirus_posts_list = coronavirus_posts[coronavirus_posts2.columns[0]].values.tolist()
coronavirus_posts_list

['@RealJamesWoods Last 18 hours:\nOur #POTUS45 ...\n✅ Huge Trump Rally in Charleston 12,000 plus\n✅ Conveens Emergency… https://t.co/E0VDvyLzpg',
 '@SecAzar WE THE PEOPLE ARE NOT* PAYING TO GET TREATED FOR THE #CORONAVIRUS. I’m reading reports Americans are recei… https://t.co/pOVP80M9xg',
 'As of 29/02/2020. Confirmed cases in areas outside PRC are picking up speed.\n#nCoV19 #coronavirus #COVID19… https://t.co/gbgc5OqPsW',
 'Pope confirmed to have #COVID19 #CoronaVirus.... Coincidence? I think NOT...',
 '@MrTommyCampbell A new case in Ajax, close to where I live.\nSick stay home.\n#coronavirus',
 'NEO-Age Art by MOnKe’J #CoronaVirusUpdate #coronavirus #CoronaVirusUpdates https://t.co/yto1sO3not',
 'There are significant announcements on #Coronavirus and hypothesizing. Time for that was 4 weeks ago. Being a panic… https://t.co/w01Eo7mrrV',
 'Yall 40-60% americans will contract this #coronavirus , thats scary af.',
 'Are we going to see over time the advantages of geographical isolation

In [20]:
X = X[1:]
Y = Y[1:]

In [21]:
X[:,:-1]

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [31]:
X_comp, X_test, Y_comp, Y_test = train_test_split(X, Y, test_size=0.2, random_state=0)
Xtr, Xva, Ytr, Yva = train_test_split(X_comp, Y_comp, test_size=0.2)

In [32]:
lr = LogisticRegression(C=2, penalty='l1')

mlp = MLPClassifier(max_iter=1000, hidden_layer_sizes=(100,), activation='identity', 
                            solver='sgd', alpha=0.01, learning_rate='adaptive')

gb = GradientBoostingClassifier(max_depth=3,loss="deviance",learning_rate=0.1,
                                 n_estimators=1500,min_samples_split=20,min_samples_leaf=9,
                                 max_features="sqrt", subsample=0.5)

In [33]:
combined = VotingClassifier(estimators=[('lr', lr), ('nn', mlp), ('gb', gb)],
                         voting='soft', flatten_transform=True) # weights=?

print("training started")
combined.fit(Xtr,Ytr)
print("training finished")

training started


C:\Users\ShiYu Qiu\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


training finished


In [34]:
X_tradewar = np.genfromtxt('X_tradewar.csv', delimiter=',')

In [35]:
X_tradewar = X_tradewar[1:]

In [80]:
tradewar_posts

(650, 220)

In [37]:
X_tradewar[:10]

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [41]:
applicarion_matrix = [combined.predict(X_tradewar), combined.predict(X_trump), combined.predict(X_coronavirus)]
print(applicarion_matrix)

[array([1., 1., 1., 0., 0., 1., 1., 1., 1., 1., 1., 1., 0., 1., 0., 1., 1.,
       1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 0., 1., 0., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 0., 1., 1., 0.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1.,
       1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1.,
       1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 0., 1., 0., 1., 1., 1., 0., 0., 1., 1., 1., 1., 1., 1., 0.,
       1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1.,
       0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 0., 1., 0., 1., 1., 1., 1., 1., 0., 0., 1., 1.,
       1., 1., 1., 1., 0., 0., 1., 1., 1., 0., 1., 0., 1., 1., 0., 0., 1.,
       1., 1., 1., 0., 1

In [42]:
application_matrix_df = pd.DataFrame(applicarion_matrix)
application_matrix_df

0     1     2     3     4     5     6     7     8     9     ...  991   \
0   1.0   1.0   1.0   0.0   0.0   1.0   1.0   1.0   1.0   1.0  ...   NaN   
1   0.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0  ...   1.0   
2   0.0   1.0   1.0   1.0   0.0   0.0   1.0   0.0   1.0   1.0  ...   1.0   

   992   993   994   995   996   997   998   999   1000  
0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
1   1.0   0.0   1.0   1.0   0.0   1.0   0.0   1.0   0.0  
2   1.0   1.0   0.0   1.0   1.0   1.0   1.0   1.0   1.0  

[3 rows x 1001 columns]

In [43]:
application_matrix_df.to_csv("application_result.csv")

In [47]:
tradewar_proba = combined.predict_proba(X_tradewar)
trump_proba = combined.predict_proba(X_trump)
coronavirus_proba = combined.predict_proba(X_coronavirus)
print(tradewar_proba, trump_proba, coronavirus_proba)

[[0.40112684 0.59887316]
 [0.47501881 0.52498119]
 [0.44156388 0.55843612]
 ...
 [0.49871825 0.50128175]
 [0.42974943 0.57025057]
 [0.43196147 0.56803853]] [[0.66700905 0.33299095]
 [0.39749063 0.60250937]
 [0.47538556 0.52461444]
 ...
 [0.60114972 0.39885028]
 [0.28256565 0.71743435]
 [0.57374749 0.42625251]] [[0.66700905 0.33299095]
 [0.42974943 0.57025057]
 [0.37592874 0.62407126]
 ...
 [0.42974943 0.57025057]
 [0.37592874 0.62407126]
 [0.38617108 0.61382892]]


In [94]:
#tradewar
positive = 0
negative = 0
neutral = 0
positive_posts = []
negative_posts = []
neutrual_posts = []

index = 0
for p in tradewar_proba:
    if p[0]>0.56: 
        positive += 1
        if p[0]>0.7:
            positive_posts.append(tradewar_posts_list[index])
    elif p[0]<0.44:
        negative += 1
        if p[0]<0.3:
            negative_posts.append(tradewar_posts_list[index])
    else:
        neutral += 1
        if p[0]>0.49 and p[0]<0.51:
            neutrual_posts.append(tradewar_posts_list[index])
    index += 1
print((positive/len(tradewar_proba))*100,"% holds a positive attitude towards tradewar")
print((negative/len(tradewar_proba))*100,"% holds a negative attitude towards tradewar")
print((neutral/len(tradewar_proba))*100,"% holds a neutral attitude towards tradewar")
print(positive_posts)
print(negative_posts)
print(neutrual_posts)

7.076923076923077 % holds a positive attitude towards tradewar
67.23076923076923 % holds a negative attitude towards tradewar
25.692307692307693 % holds a neutral attitude towards tradewar
['Did you miss this Gary Shilling Interview? With recent #coronavirusupdates we now know that the Coronavirus has spr… https://t.co/g4XULnUmbF', "She forgot #obama🙄\r\n\r\nThis loony is running for office. Obviously she'll never get elected, but still.\r\n\r\nI heard somew… https://t.co/8FMhtjcDas", 'China’s cabinet makers lose US anti-dumping case as trade tensions remain despite phase one deal #tradewar… https://t.co/bRbeLESNww', 'China’s cabinet makers lose US anti-dumping case as trade tensions remain despite phase one deal, reports \u2066@Lee_AHY… https://t.co/r75rMnfDkr', 'Bad year for #trade as it records the first decline in a decade - #economy #wealth #GDP #tradewar… https://t.co/GwHIvDhNDp', '#TradeWar Who will win? Who are to blame?\r\n\r\nre: China Is the Real Sick Man of Asia https://t.c

In [55]:
#tradewar_proba_list = tradewar_proba.values.to_list()
tradewar_proba

array([[0.40112684, 0.59887316],
       [0.47501881, 0.52498119],
       [0.44156388, 0.55843612],
       ...,
       [0.49871825, 0.50128175],
       [0.42974943, 0.57025057],
       [0.43196147, 0.56803853]])

In [97]:
#trump
positive = 0
negative = 0
neutral = 0
positive_posts = []
negative_posts = []
neutrual_posts = []

index = 0
for p in trump_proba:
    if p[0]>0.57: 
        positive += 1
        if p[0]>0.7:
            positive_posts.append(trump_posts_list[index])
    elif p[0]<0.43:
        negative += 1
        if p[0]<0.3:
            negative_posts.append(trump_posts_list[index])
    else:
        neutral += 1
        if p[0]>0.49 and p[0]<0.51:
            neutrual_posts.append(trump_posts_list[index])
    index += 1
    
print((positive/len(trump_proba))*100,"% holds a positive attitude towards trump")
print((negative/len(trump_proba))*100,"% holds a negative attitude towards trump")
print((neutral/len(trump_proba))*100,"% holds a neutral attitude towards trump")
print(positive_posts)
print(negative_posts)
print(neutrual_posts)

8.291708291708291 % holds a positive attitude towards trump
67.13286713286713 % holds a negative attitude towards trump
24.575424575424577 % holds a neutral attitude towards trump
['#TRUMP ADMINISTRATION CONSIDERING IMPOSING ENTRY #RESTRICTIONS AT #BORDER WITH #MEXICO OVER CORONAVIRUS THREAT - U.… https://t.co/Ucpn6n5T3L', 'Could #Comcast sue #Trump for defamation? https://t.co/TLrxc3WgnR', 'This time some people will die from #Trump’s cynicism. https://t.co/bcfxhdbL3e', '#Trump Allies Hope to Ride Anti-Socialist Rhetoric to #Election #Win https://t.co/N7jShdQNku https://t.co/5OJR2p3II2', '@rodcain @OrsonJTrump @krystalball @esaagar In 2014 Steve Bannon studied how ISIS used #facebook to recruit across… https://t.co/m8cVOPk0C9', 'Just saw a car sticker that said, “Trump skis in jeans” 🤣👏🏼 \r\n\r\n#trump #vail', '#Trump is the most dangerous despot in the world #COVID19 #TrumpLiesAboutCoronavirus No #hoax @VP. @CDCgov @WHO… https://t.co/vm3lSuOK2J', "I just listed: 'A Season's Promise',

In [98]:
#coronavirus
positive = 0
negative = 0
neutral = 0
positive_posts = []
negative_posts = []
neutrual_posts = []

index = 0
for p in coronavirus_proba:
    if p[0]>0.57: 
        positive += 1
        if p[0]>0.7:
            positive_posts.append(coronavirus_posts_list[index])
    elif p[0]<0.43:
        negative += 1
        if p[0]<0.3:
            negative_posts.append(coronavirus_posts_list[index])
    else:
        neutral += 1
        if p[0]>0.49 and p[0]<0.51:
            neutrual_posts.append(coronavirus_posts_list[index])
    index += 1
    
print((positive/len(coronavirus_proba))*100,"% holds a positive attitude towards coronavirus")
print((negative/len(coronavirus_proba))*100,"% holds a negative attitude towards coronavirus")
print((neutral/len(coronavirus_proba))*100,"% holds a neutral attitude towards coronavirus")
print(positive_posts)
print(negative_posts)
print(neutrual_posts)

9.79020979020979 % holds a positive attitude towards coronavirus
62.83716283716284 % holds a negative attitude towards coronavirus
27.372627372627374 % holds a neutral attitude towards coronavirus
['#BREAKING: Health officials confirm a 4th case of #coronavirus in Santa Clara County. An adult woman, who is a hous… https://t.co/7q0kbnYbNy', '@ScottMorrisonMP Hmmm, #ScottyFromMarketting led the world in handling the #coronavirus crisis?  Considering, it st… https://t.co/WwWAOOqvnC', 'Little hero!\nhttps://t.co/SEGQxn5mNL\n#coronavirus #Baby', 'Worth watching a few minutes to contrast the level of professionalism with the earlier WH #coronavirus presser .... https://t.co/6MNGqtyJOG', '@financialpost Are the curtains impenetrable to #coronavirus though?  🤪', '@BebeRexha your response you deserve my dear about your @amazon purchase, it got buried.\n\n#coronavirus #hoax #Purge… https://t.co/UxElk5xNdT', 'Do you know what it is like to live as a foreigner in Japan?#mainichi #nihon #japan #jap