In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.neural_network import MLPClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import VotingClassifier

In [3]:
import joblib
combined = joblib.load('../new_data/best_combined.sav')

## Trump

In [6]:
trump_posts = pd.read_csv('../application_dataset/trump1.csv')
trump_posts2 = trump_posts.drop(trump_posts.columns[0], axis=1)
trump_posts_list = trump_posts[trump_posts2.columns[0]].values.tolist()
trump_posts_list[:5]

['Government is us. \n\nWhen you run to dismantle it, you run to dismantle all of us. \n\nIs anyone really surprised this is happening to our country? \n\n#NoTestsAvailable #itwillmagicallydisappear #DemocratHoax #cutfunding #denial #pandemic #Trump',
 'The #existentialThreat is a system that hatches fascist politicians like #Trump, leaves 10s of millions of ppl w inadequate #healthcare, burns the planet 4 profit w #ClimateChange, &amp; sees almost every1 working day-2-day w nothing to show. #biden is that threat. #bernie is cure.',
 'True Story." 😂😂😂 \n[[Follow 4 more]] \nTAGS: \n#FUNNY #COMEDY #VOICEOVER #POSTONEOFYOURV #MADLIPZ #ACTING #LIPSYNC #DUBS #VOICEACTING #TRUMP #PARODY #CARRER #DUB #PRESIDENT https://t.co/h87pxiUPE8',
 'Right to try can reduce the timeline #trump #fda #coronavirus $xlv https://t.co/Z0Mwg6uxX9',
 '@realDonaldTrump @DonaldJTrumpJr @WhiteHouse @BernieSanders @JoeBiden There you have it folks. The #potus seeking to profit from a vaccine for the #coronavirus \n#

In [11]:
X_trump = np.genfromtxt('../new_data/trump_word2vec.csv', delimiter=',')[1:]
X_trump

array([[ 0.16489711,  0.15533015,  0.11092234, ..., -0.15210468,
         0.05749126,  0.06981257],
       [ 0.07456058,  0.10522122,  0.15535699, ..., -0.12861408,
         0.06724104, -0.03129557],
       [-0.07109759,  0.18972147,  0.08808867, ..., -0.0904436 ,
        -0.06222776, -0.00197694],
       ...,
       [-0.01313951,  0.17847665,  0.04369592, ...,  0.03429232,
         0.04318616,  0.0238566 ],
       [ 0.02311338,  0.08130767,  0.22410049, ..., -0.07082635,
         0.0681502 , -0.01249944],
       [ 0.04915699,  0.07476464,  0.2698985 , ..., -0.07652553,
        -0.09977458, -0.05255711]])

In [13]:
Y_trump = combined.predict_proba(X_trump)
Y_trump

array([[0.79254253, 0.20745747],
       [0.60298945, 0.39701055],
       [0.09207115, 0.90792885],
       ...,
       [0.13195464, 0.86804536],
       [0.87561226, 0.12438774],
       [0.45863655, 0.54136345]])

In [14]:
#trump
positive = 0
negative = 0
neutral = 0

positive_list, negative_list = [], []

for i,p in enumerate(Y_trump):

    if p[1] > 0.6: 
        positive += 1
        if p[1] > 0.9:
            positive_list.append(trump_posts_list[i])

    elif p[1] < 0.4:
        negative += 1
        if p[1] < 0.1:
            negative_list.append(trump_posts_list[i])
    else:
        neutral += 1
    
print((positive/len(Y_trump))*100,"% holds a positive attitude towards trump")
print((negative/len(Y_trump))*100,"% holds a negative attitude towards trump")
print((neutral/len(Y_trump))*100,"% holds a neutral attitude towards trump")

print('\n\n\n')
print("Positive:")
for p in positive_list:
    print(p)
    
print('\n\n\n')
print("Negative:")
for p in negative_list:
    print(p)

38.2 % holds a positive attitude towards trump
29.299999999999997 % holds a negative attitude towards trump
32.5 % holds a neutral attitude towards trump




Positive:
True Story." 😂😂😂 
[[Follow 4 more]] 
TAGS: 
#FUNNY #COMEDY #VOICEOVER #POSTONEOFYOURV #MADLIPZ #ACTING #LIPSYNC #DUBS #VOICEACTING #TRUMP #PARODY #CARRER #DUB #PRESIDENT https://t.co/h87pxiUPE8
#Trump-kins:

Proud of Racism,
Proud of Greed &amp; Corruption,
Proud of Immorality,

Now, many are proud that #TrumpPlague w/ harm/kill others

SMH🤦🏼‍♂️ = i really do not understand https://t.co/7ZnLY51zcx
What a dirtbag #Trump #COVID19   https://t.co/PtqWEuntAE
@f_mols All #Trump has is “tremendous” and “incredible” He is totally “incredible”
⬇️⬇️⬇️⬇️👏👏👏👏👏😆😆😆😆🗣️🗣️🗣️🗣️🎯🎯🎯🎯🎯

#TRUTH W A CAPITAL T &amp; it's not for #Trump!! #TrumpPlague #TrumpIsTheWORSTPresidentEVER #ShutItDown #COVID19 #CoronaVirusUpdates #StayHome #SocialDistancingNow #WhereAreTheTestKits #TrumpVirus #TrumpVirusCoverup #DemocraticDebate 😷🚨 https://t.co/rvJx9vbKD

## coronavirus

In [16]:
coronavirus_posts = pd.read_csv('../application_dataset/coronavirus1.csv')
coronavirus_posts2 = coronavirus_posts.drop(coronavirus_posts.columns[0], axis=1)
coronavirus_posts_list = coronavirus_posts[coronavirus_posts2.columns[0]].values.tolist()
coronavirus_posts_list[:5]

['FIRST 1-on-1 Democratic Debate on NOW.\n\nWatch:\nhttps://t.co/Ia3dpBk43R\nhttps://t.co/fmKIXgU44g\nhttps://t.co/iicO2BVela\n\n#notmeus #covid_19 #covıd19 #coronavirus #coronavirusoutbreak⚠️ #medicareforall #unbought #bernie2020 #berniebeatstrump https://t.co/vZ8WVCkf56',
 'Stay safe, everyone. This, too, shall pass.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n#staycalm #quarantine #quarantineandchill #socialdistancing #covid_19 #coronavirus #washyourhands https://t.co/zjbvT5PfwM',
 '@ProudResister @renbri13542 @JohnCooper4Nash @GovBillLee - with Steve Smith refusing to comply, this what we need to see here. He is putting tourists at risk, tourists who will return home to THEIR communities. #coronavirus #coronavirusnashville #NashvilleTN #nashville',
 'CNN DEBATE RIGHT NOW: Joe Biden said he would put the military out on the streets now, during this national emergency. @CNN #coronavirus #DemocraticDebate https://t.co/pnuaRWXPVg',
 'There are now more confirmed #coronavirus cases outside China tha

In [18]:
X_coronavirus = np.genfromtxt('../new_data/coronavirus_word2vec.csv', delimiter=',')[1:]
X_coronavirus

array([[-0.03009885,  0.28107452,  0.09581375, ...,  0.04882917,
        -0.04373717, -0.12045257],
       [ 0.26245296,  0.30704144,  0.39360133, ..., -0.24031438,
        -0.07129192,  0.4948717 ],
       [ 0.08601478,  0.20926178,  0.16468643, ..., -0.13506167,
         0.04698234, -0.04918837],
       ...,
       [ 0.18450731,  0.27161598,  0.20425725, ...,  0.08223472,
        -0.1359793 , -0.13023856],
       [-0.00287298,  0.22350828,  0.1119098 , ..., -0.03568802,
         0.05357343, -0.07201127],
       [ 0.07736453,  0.21726328,  0.14261918, ..., -0.05755896,
         0.03231025, -0.07331132]])

In [20]:
Y_coronavirus = combined.predict_proba(X_coronavirus)
Y_coronavirus

array([[0.46295138, 0.53704862],
       [0.43279714, 0.56720286],
       [0.58812292, 0.41187708],
       ...,
       [0.63067549, 0.36932451],
       [0.62173704, 0.37826296],
       [0.73833717, 0.26166283]])

In [21]:
positive = 0
negative = 0
neutral = 0

positive_list = []
negative_list = []

for i,p in enumerate(Y_coronavirus):

    if p[1] > 0.6: 
        positive += 1
        if p[1] > 0.9:
            positive_list.append(coronavirus_posts_list[i])

    elif p[1] < 0.4:
        negative += 1
        if p[1] < 0.1:
            negative_list.append(coronavirus_posts_list[i])
    else:
        neutral += 1
    
print((positive/len(Y_coronavirus))*100,"% holds a positive attitude towards coronavirus")
print((negative/len(Y_coronavirus))*100,"% holds a negative attitude towards coronavirus")
print((neutral/len(Y_coronavirus))*100,"% holds a neutral attitude towards coronavirus")

for p in positive_list:
    print(p)
    
print('\n\n\n')
print("Negative:")
for p in negative_list:
    print(p)

30.3 % holds a positive attitude towards coronavirus
41.699999999999996 % holds a negative attitude towards coronavirus
28.000000000000004 % holds a neutral attitude towards coronavirus
The #Celebrity Coronavirus tracker is out. Follow along here: https://t.co/7oZQcPpJyo #coronavirus
Beautiful evening here in Jensen. Calm before the storm?#jensenbeach #coronavirus #772living @ Pineapple Jacks Bistro https://t.co/x1EotcJ435
Grade 1 adding their own sounds to the story “Little Indian Boy”. Connecting the actions in a story to different sounds they can create. Excited for the level of creativity this gives. #pypchat #music #onlinelearning #elearning #coronavirus https://t.co/RlsyMPT55k
Hey America..
#coronavirus
 #COVID19
#StayTheFHome https://t.co/1KKK28gDOx
It is #habbening Movie
#كورونا #coronavirus #TheStormHasArrived https://t.co/GQx64c41H1
@MDolf @LDrogosPhD ❤️ Crafting a #coronavirus from #pipecleaners was helpful too 🦠🎨🧠 LEARN MORE 🤓👉🏾 https://t.co/hnrVcipjSc https://t.co/ObI4BRcq

## MeToo

In [23]:
metoo_posts = pd.read_csv('../application_dataset/Metoomovement1.csv')
metoo_posts2 = metoo_posts.drop(metoo_posts.columns[0], axis=1)
metoo_posts_list = metoo_posts[metoo_posts2.columns[0]].values.tolist()
metoo_posts_list[:5]

['What is worse - ruining @PlacidoDomingo for personal reasons or writing #lies for those who are doing it? Unscrupulous mercenaries!\n @elpaissemanal @el_pais @elpais_cultura #PlácidoDomingo #opera #tenor #metoo #metoomovement  #feminismo https://t.co/jJRN8udZIk',
 'Will these #lies ever stop?! Shameful and shameless!\n\n#PlacidoDomingo #PlácidoDomingo #opera #tenor #metoo #metoomovement  #feminismo #mentiras @elpaisuy @elpais_america @elpais_espana @elpais_cultura https://t.co/L0bMyz3KhP https://t.co/6PQbA6gyi6',
 'Please vote 4 my book cover for cover of the month. Help others with child loss, grief, #abuse. #rape https://t.co/yfHkxsHNKj #DomesticAbuse #ChildhoodCancer Thank you kindly. #ASMSG #IARTG #metoomovement #DomesticAbuse #Romance #CR4U #ADHD #specialneeds #CoPromosRT',
 'And honestly. There needs to be a clearer cut definition for snitch and rape. Cause the situations I’m hearing about people being labeled as a snitch isn’t technically snitching. Along with rape. It’s women

In [25]:
X_metoo = np.genfromtxt('../new_data/Metoomovement_word2vec.csv', delimiter=',')[1:]
X_metoo

array([[-0.0185164 ,  0.2499859 ,  0.12702811, ..., -0.10466733,
         0.03403067,  0.00356049],
       [-0.03891921,  0.2620171 ,  0.08575037, ..., -0.06342452,
        -0.01427911, -0.04138988],
       [ 0.002216  ,  0.23587711,  0.02129001, ..., -0.08602763,
         0.02059182,  0.1667108 ],
       ...,
       [ 0.14207678,  0.0786264 ,  0.21403322, ..., -0.03408537,
        -0.06486704,  0.0035299 ],
       [ 0.01111663,  0.22482179,  0.15812479, ..., -0.06723486,
         0.03835816,  0.06576356],
       [ 0.14251898,  0.35406438,  0.19423215, ..., -0.22997963,
         0.01901244,  0.0129883 ]])

In [26]:
Y_metoo = combined.predict_proba(X_metoo)
Y_metoo[:5]

array([[0.80868162, 0.19131838],
       [0.56242412, 0.43757588],
       [0.29273813, 0.70726187],
       [0.61941142, 0.38058858],
       [0.42760943, 0.57239057]])

In [27]:
positive = 0
negative = 0
neutral = 0

positive_list = []
negative_list = []

for i,p in enumerate(Y_metoo):

    if p[1] > 0.6: 
        positive += 1
        if p[1] > 0.9:
            positive_list.append(metoo_posts_list[i])

    elif p[1] < 0.4:
        negative += 1
        if p[1] < 0.1:
            negative_list.append(metoo_posts_list[i])
    else:
        neutral += 1
    
print((positive/len(Y_metoo))*100,"% holds a positive attitude towards metoo")
print((negative/len(Y_metoo))*100,"% holds a negative attitude towards metoo")
print((neutral/len(Y_metoo))*100,"% holds a neutral attitude towards metoo")

print('\n\n\n')
print("Positive:")
for p in positive_list:
    print(p)
    
print('\n\n\n')
print("Negative:")
for p in negative_list:
    print(p)

41.52542372881356 % holds a positive attitude towards metoo
27.75423728813559 % holds a negative attitude towards metoo
30.720338983050848 % holds a neutral attitude towards metoo




Positive:
Happy 87th Birthday Ruth Bader Ginsburg

...The women who inspired Ruth and the women she’s inspired.

 #supremecourt #law #birthdays #RBG #inspiration #metoomovement #women #lawyers #justiceforall #socialimpact https://t.co/tG45Ydlr5P
@thatsSOlaura_ Women proposing is a Trend now it’s the new #Metoomovement 😅😂
“The #Metoomovement is not a witch hunt. It is a reckoning.” - Actress #JessicaBarth https://t.co/OOXO9zPsHN @Variety https://t.co/mMvOGzEbFx
#Metoomovement This is its success. 

Way to go for keeping workplaces safe. 

https://t.co/vu520Dmu1v
Agreed #TimesUp #Metoomovement #EnoughIsEnough https://t.co/lXzAkG77Lx
Sicko!  @Erin_MA_Shean thank you for sharing your touching story. I support you! #Metoomovement #strength https://t.co/bfcpDv2Jp9
@LaurelSchuett If there is such a thing as Divi